# Generated by Django 3.2.16 on 2025-06-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientGenotype',
            fields=[
                ('patient_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('genotype_string', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('variant_id', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
                ('qual', models.FloatField()),
                ('ac', models.IntegerField()),
                ('af', models.FloatField()),
                ('an', models.IntegerField()),
            ],
        ),
    ]
