# Generated by Django 3.2.16 on 2025-06-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='unique_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
