# Generated by Django 3.2.16 on 2025-06-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variantapp', '0002_variant_unique_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='qual',
        ),
    ]
