# Generated by Django 5.2.3 on 2025-07-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variantapp', '0003_remove_variant_qual'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientgenotype',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientgenotype',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
